CREATE SCHEMA IF NOT EXISTS cards;

CREATE TABLE cards.TB_SHUFFLE(
    SUCCESS BOOLEAN NOT NULL,
	DECK_ID VARCHAR(50) NOT NULL PRIMARY KEY,
	SHUFFLE BOOLEAN NOT NULL,
	REMAINING NUMERIC NOT NULL
);

CREATE TABLE cards.TB_HANDS(
    ID SERIAL PRIMARY KEY,
    PLAYER VARCHAR(50) NOT NULL,
    DECK_ID VARCHAR(50) NOT NULL,
    CARD VARCHAR(50) NOT NULL
);